Initial
codex-team/hawk.desktop pull request #1
Opened 2019-04-08 18:44 UTC by DorofeevMark

2019-04-12 05:19 UTC, kabachook commented
Не работает vue приложение, выкидывается листинг файлов

2019-04-12 05:20 UTC, neSpecc requested changes

2019-04-12 05:20 UTC, neSpecc commented on .electron-vue/build.js
> +'use strict'
не понимаю суть всех этих файлов. Думаю, нам не нужен electron-vue, тк мы не будем тут собирать vue, а будем использовать уже готовое приложение. Надо сделать просто обычное базовое электрон-приложение, которое будет показывать окно с уже собранным гаражом

2019-04-15 19:20 UTC, kabachook requested changes

2019-04-15 19:20 UTC, kabachook commented on README.md
> +npm run lint
Надо убрать лишнее из ридми после бутстрапа

2019-04-15 19:20 UTC, kabachook commented on package.json
> +    "update": "git submodule foreach git pull origin vue-config-addition && cd hawk.garage && git checkout vue-config-addition && yarn install && yarn build"
Давай добавим что-то вроде `prepare`, которое будет только билдить гараж, а её встроить в эту комманду

2019-04-17 18:33 UTC, kabachook approved these changes

2019-04-19 10:44 UTC, talyguryn commented on package.json
> +  "devDependencies": {
```suggestion
  "dependencies": {
```

2019-04-20 10:38 UTC, neSpecc approved these changes

2019-04-20 10:38 UTC, neSpecc commented on package.json
> +    "submodule:build": "cd hawk.garage && git checkout vue-config-addition && yarn install && yarn build",
что такое vue-config-addition ?

2019-04-20 11:18 UTC, DorofeevMark commented on package.json
> +  "devDependencies": {
В документации электрона рекомендуют в дев зависимости добавлять

2019-04-20 11:19 UTC, merged

2019-04-20 20:53 UTC, neSpecc approved these changes