Add top bar
codex-team/hawk.desktop pull request #29
Opened 2021-06-08 20:59 UTC by talyguryn

resolves #26

2021-06-15 18:12 UTC, neSpecc requested changes

2021-06-15 18:12 UTC, neSpecc commented on bin/inject-script.js
> +const missingHTML = `
можно вынести это в отдельный шаблон?

2021-06-17 09:04 UTC, nikmel2803 requested changes
доки для запуска неактуальны

2021-06-17 09:25 UTC, nikmel2803 commented on bin/inject-script.js
> +const fs = require('fs');
стоило бы в начале сделать коммент про то, что этот файл делает и зачем он нужен
типо так
```
/**
 * @file
 */ 
```

2021-07-18 06:54 UTC, robonetphy commented on bin/inject-script.js
> +      win.setFullScreen(!win.isFullScreen());
I guess this must be 
`win.isMaximized() ? win.unmaximize() : win.maximize();`

2021-08-22 18:13 UTC, ilyamore88 approved these changes

2021-08-22 19:20 UTC, merged