redirect request to index.html
codex-team/hawk.desktop pull request #4
Opened 2019-04-26 07:29 UTC by nikmel2803

2019-04-26 07:36 UTC, neSpecc approved these changes

2019-04-26 17:13 UTC, DorofeevMark requested changes
Можно сразу начать выносить в отдельные файлы, чтобы не раздувать main.
Например, все взаимодействия с протоколом вынести в protocols.js и оттуда импортировать

2019-04-26 17:15 UTC, DorofeevMark commented on src/main.js
> +  }, function (error) {
```suggestion
  }, (error) => {
```

2019-04-29 11:49 UTC, DorofeevMark requested changes
Давай лучше будем экспортировать функцию из protocols.js и вызывать ее

2019-04-29 11:49 UTC, DorofeevMark commented on src/protocols.js
> +protocol.interceptFileProtocol('file', function (req, callback) {
```suggestion
protocol.interceptFileProtocol('file', (req, callback) => {
```

2019-04-29 12:39 UTC, DorofeevMark approved these changes

2019-04-29 13:30 UTC, merged